api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/api_plateform/']
        
    patch_formats:
        json:       ['application/json']
        
    formats:
        json:       ['application/json']
        html:       ['text/html']
        form:
            mime_types: ['multipart/form-data']
    swagger:
        versions: [3]
